name: video_label
channels:
  - defaults
dependencies:
  - ca-certificates=2025.2.25
  - libffi=3.4.4
  - openssl=3.0.16
  - pip=24.2
  - python=3.8.20
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
    - numpy==1.24.4
    - opencv-python==4.11.0.86
    - pyqt5==5.15.11
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.15.0
